package com.hbmtweaks;

/**
 * 生成带中文使用说明的空配置模板（首次启动写入 config/hbmtweak/hbmtweaks.json）。
 *
 * 说明以 "_comment" 字段写入 JSON——Gson 解析时会忽略未知字段，不影响读取。
 * 玩家填写后这些说明字段会被保留在文件中（解析时忽略，保存时原样输出）。
 */
public class ConfigTemplateWriter {

    public static String buildTemplateJson() {
        return "{\n"
                + "  \"_comment\": \"HBM Tweaks 配置文件 - 所有条目默认空，按需填写后重启游戏生效\\n"
                + "    优先级：玩家自定义项 > 全局数值 > HBM 原版数值\\n"
                + "    规则：某类别只要填写了任意一个自定义项，该类别的全局数值自动禁用\\n"
                + "    完整可用的 ID 列表见同目录 hbm_tweaks_ids.txt\\n"
                + "    全部数值均可单独调整，未填写的保持 HBM 原版数值\",\n"
                + "\n"
                + "  \"_weapons_usage\": \"武器/弹种单独调整（bullets: 用 hbm_tweaks_ids.txt 中 weapons 部分的 bulletName）\\n"
                + "    示例: { \\\"bulletName\\\": \\\"g12\\\", \\\"damageMult\\\": 1.5, \\\"penetrate\\\": true }（示例仅展示格式，数值自定）\\n"
                + "    可用字段: bulletName(弹种名), damageMult(伤害倍率), damageSet(直接设定伤害系数), armorPiercing(穿甲0~1), thresholdNegation(护甲阈值穿透), knockback(击退), headshotMult(爆头倍率), spreadMult(散布倍率<1更准), velocityMult(弹速倍率), penetrate(true/false穿透), rateOfFireMult(仅旧枪械)\",\n"
                + "  \"globalDamageMult\": 1.0,\n"
                + "  \"globalRateOfFireMult\": 1.0,\n"
                + "  \"globalAmmoCapMult\": 1.0,\n"
                + "  \"weapons\": [],\n"
                + "\n"
                + "  \"_guns_usage\": \"武器本体单独调整（item: 枪械物品注册名，见 ids 文件 guns 部分；与弹种倍率相乘）\\n"
                + "    用于修复同口径共享倍率导致的偏差（如 9mm 冲锋枪 lag 比其它 9mm 枪基础伤害高 8 倍）\\n"
                + "    示例: { \\\"item\\\": \\\"hbm:gun_m2\\\", \\\"damageMult\\\": 1.5 }（示例仅展示格式，数值自定）\",\n"
                + "  \"guns\": [],\n"
                + "\n"
                + "  \"_melee_usage\": \"HBM 近战武器/工具调整（剑/镐/斧/铲/电锯/扳手等可当武器的物品）\\n"
                + "    纯显式：tools 配置了才生效（未配置 = 原版，模组不做隐式乘法）\\n"
                + "    tools: { item(注册名见 ids 文件 tools 部分), damageSet(绝对目标伤害) 或 damageMult(倍率) }\\n"
                + "    示例: { \\\"item\\\": \\\"hbm:dnt_sword\\\", \\\"damageSet\\\": 3.0 } 或 { \\\"item\\\": \\\"hbm:chainsaw\\\", \\\"damageMult\\\": 0.5 }（示例仅展示格式，数值自定）\",\n"
                + "  \"tools\": [],\n"
                + "\n"
                + "  \"_mobs_usage\": \"怪物单独调整（entityClass: 用 ids 文件 mobs 部分的类名）\\n"
                + "    示例: { \\\"entityClass\\\": \\\"com.hbm.entity.mob.EntityGlowingOne\\\", \\\"healthMult\\\": 1.5, \\\"damageCap\\\": 20.0 }（示例仅展示格式，数值自定）\\n"
                + "    可用字段: entityClass(实体类名), healthMult(血量倍率), healthSet(直接设定血量上限, 如100=固定100血), damageMult(近战攻击倍率), outgoingDamageMult(该怪造成的一切伤害倍率: 近战/弹道/爆炸), speedMult(速度倍率), knockbackResist(击退抗性 0~1), damageCap(单次受伤上限), projectileDamageMult(弹道伤害倍率), explosionDamageMult(爆炸伤害倍率), fireImmune(火焰免疫 true/false), magicImmune(魔法免疫 true/false)\",\n"
                + "  \"globalMobHealthMult\": 1.0,\n"
                + "  \"globalMobDamageMult\": 1.0,\n"
                + "  \"mobs\": [],\n"
                + "\n"
                + "  \"_turret_damage_usage\": \"炮台直接伤害倍率（陶子炮/微波炮/特斯拉类等无实体来源伤害）\\n"
                + "    注意: 必须同时把 enableTurretDamageOverride 设为 true 才生效\\n"
                + "    弹种型炮台（哨戒/切科夫/霍华德/战列/导弹）随对应弹种倍率自动压缩，不受此项影响\",\n"
                + "  \"enableTurretDamageOverride\": false,\n"
                + "  \"turretDamageMult\": 1.0,\n"
                + "\n"
                + "  \"_grenade_usage\": \"投掷物（手榴弹）伤害倍率\\n"
                + "    grenades: 按装药枚举名（POWDER/HE/DEMO/INC/WP/CLUSTER/EMP/PLASMA/LASER/CLUSTER_HEAVY/NUCLEAR/NUCLEAR_DEMO/SCHRAB）\\n"
                + "      或物品注册名（hbm:stick_dynamite / hbm:stick_dynamite_fishing）覆写（显式最终倍率，未配置 = 原版）\\n"
                + "      示例: { \\\"filling\\\": \\\"HE\\\", \\\"damageMult\\\": 1.5 } 或 { \\\"item\\\": \\\"hbm:stick_dynamite\\\", \\\"damageMult\\\": 1.2 }（示例仅展示格式，数值自定）\\n"
                + "    dynamiteDamageMult: 炸药棒 / 钓鱼炸药（MC 原版爆炸）单点倍率\\n"
                + "    集束/激光破片弹种（fragmentation/pellets/pellets_heavy/laser）在 weapons 列表按弹种名调整\\n"
                + "    注意: 必须同时把 enableGrenadeOverride 设为 true 才生效\",\n"
                + "  \"enableGrenadeOverride\": false,\n"
                + "  \"dynamiteDamageMult\": 1.0,\n"
                + "  \"grenades\": [],\n"
                + "\n"
                + "  \"_artillery_usage\": \"炮击炮弹爆炸伤害倍率（Arty 炮兵阵地 / HIMARS）\\n"
                + "    注意: 必须同时把 enableArtilleryOverride 设为 true 才生效\",\n"
                + "  \"enableArtilleryOverride\": false,\n"
                + "  \"artilleryDamageMult\": 1.0,\n"
                + "\n"
                + "  \"_foods_usage\": \"食物单独调整（item: 用 ids 文件 foods 部分的注册名，罐头带meta如 hbm:canned_conserve:8）\\n"
                + "    示例: { \\\"item\\\": \\\"hbm:cheese\\\", \\\"hunger\\\": 5 }\\n"
                + "    可用字段: item(物品注册名), hunger(饥饿值=半鸡腿数), saturation(饱和度系数)\",\n"
                + "  \"foods\": [],\n"
                + "\n"
                + "  \"_nukes_usage\": \"核弹单独调整（field: 用 ids 文件 nukes 部分的 BombConfig 字段名）\\n"
                + "    注意: 必须同时把 enableNukeOverride 设为 true 才生效（避免与 hbm.cfg 冲突）\\n"
                + "    示例: { \\\"field\\\": \\\"tsarRadius\\\", \\\"value\\\": 800 }\",\n"
                + "  \"enableNukeOverride\": false,\n"
                + "  \"nukes\": [],\n"
                + "\n"
                + "  \"_turrets_usage\": \"炮台单独调整（entityClass: 用 ids 文件 turrets 部分的类名）\\n"
                + "    示例: { \\\"entityClass\\\": \\\"com.hbm.tileentity.turret.TileEntityTurretSentry\\\", \\\"range\\\": 48.0 }\\n"
                + "    可用字段: entityClass(炮台类名), range(检测范围), consumption(耗电HE/t), yawSpeed(转速)\",\n"
                + "  \"turrets\": []\n"
                + "}\n";
    }
}
